# Generated by Django 3.2 on 2021-04-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20210420_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_name', models.CharField(max_length=200)),
                ('new_Image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='upload_old',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_name', models.CharField(max_length=200)),
                ('old_Image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='upload',
        ),
    ]
